# Generated by Django 3.1.4 on 2021-01-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(blank=True, max_length=200)),
                ('seller_id', models.CharField(max_length=20, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('industry', models.CharField(max_length=50)),
                ('acc_no', models.CharField(max_length=50, null=True)),
                ('acc_name', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('bvn', models.CharField(max_length=30, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
                'db_table': 'Merchant_tb',
            },
        ),
    ]
