# Generated by Django 3.1.4 on 2021-01-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_merchant_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='details',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='merchant',
            name='owner',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
