# Generated by Django 3.1.4 on 2021-01-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210119_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('accNumber', models.CharField(blank=True, max_length=150)),
                ('accName', models.CharField(max_length=150)),
                ('bank', models.CharField(max_length=150)),
                ('subAcc', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dispatcher',
                'verbose_name_plural': 'Dispatchers',
                'db_table': 'Dispatch_tb',
            },
        ),
    ]
