# Generated by Django 3.1.4 on 2021-01-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_dispatcher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatcher',
            old_name='subAcc',
            new_name='subAcc_id',
        ),
        migrations.AddField(
            model_name='merchant',
            name='subAcc_id',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
