# Generated by Django 3.1.4 on 2021-01-17 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.merchant')),
            ],
            options={
                'verbose_name': 'Store Category',
                'verbose_name_plural': 'Store Categories',
                'db_table': 'StoreCategory_tb',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=800, null=True)),
                ('discount', models.CharField(max_length=12, null=True)),
                ('price', models.CharField(max_length=12)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.merchant')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Product_tb',
            },
        ),
    ]
