# Generated by Django 3.1.4 on 2021-01-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_category',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='store_category',
            name='industry',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
