# Generated by Django 3.1.4 on 2021-01-17 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0002_auto_20210117_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='merchant_id',
        ),
        migrations.AddField(
            model_name='product',
            name='store_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Estore.store_category'),
            preserve_default=False,
        ),
    ]
