# Generated by Django 3.1.4 on 2021-01-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0003_auto_20210117_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodImg2',
            field=models.ImageField(blank=True, default='assets/img/prodPlaceholder.jpg', null=True, upload_to='productPics'),
        ),
        migrations.AddField(
            model_name='product',
            name='prodImg3',
            field=models.ImageField(blank=True, default='assets/img/prodPlaceholder.jpg', null=True, upload_to='productPics'),
        ),
        migrations.AddField(
            model_name='product',
            name='prodImg4',
            field=models.ImageField(blank=True, default='assets/img/prodPlaceholder.jpg', null=True, upload_to='productPics'),
        ),
        migrations.AddField(
            model_name='product',
            name='prodImgMain',
            field=models.ImageField(default='assets/img/prodPlaceholder.jpg', upload_to='productPics'),
        ),
    ]
