# Generated by Django 3.1.4 on 2021-01-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0005_auto_20210119_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='thum_img',
            field=models.ImageField(blank=True, default='assets/img/prodPlaceholder.jpg', upload_to='categoryPics'),
        ),
    ]
