# Generated by Django 3.1.4 on 2021-01-19 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210118_0150'),
        ('Estore', '0007_auto_20210119_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Shop',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.merchant'),
            preserve_default=False,
        ),
    ]
