# Generated by Django 3.1.4 on 2021-01-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0009_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
    ]
