# Generated by Django 3.1.4 on 2021-01-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0010_cart_cleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodImg2',
            field=models.ImageField(blank=True, default='assets/img/prodPlaceholder.jpg', null=True, upload_to='media/productPics'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodImg3',
            field=models.ImageField(blank=True, default='assets/img/prodPlaceholder.jpg', null=True, upload_to='media/productPics'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodImg4',
            field=models.ImageField(blank=True, default='assets/img/prodPlaceholder.jpg', null=True, upload_to='media/productPics'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodImgMain',
            field=models.ImageField(default='assets/img/prodPlaceholder.jpg', upload_to='media/productPics'),
        ),
    ]
